spring.application.name=PRODUCT-SERVICE
server.port=8181
# ===============================

#===========Eureka Server Configuration=====================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/product_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true